# Generated by Django 5.2.5 on 2025-08-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_post_categoria_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instrucciones',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones'),
        ),
        migrations.AddField(
            model_name='post',
            name='receta',
            field=models.TextField(blank=True, null=True, verbose_name='Receta'),
        ),
    ]
