# Generated by Django 5.2.5 on 2025-08-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_categoria_post_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='blog.categoria'),
        ),
    ]
